spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: customers
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka/