server:
  port: 8078
  
spring:
  application: 
    name: proxy-service
    
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://172.16.24.195:8761/eureka
#      defaultZone: http://localhost:8761/eureka

