vets:
  cache:
    ttl: 60
    heap-size: 100

spring:
  profiles: dev
  application: 
    name: vets
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  client: 
    service-url: 
      defaultZone: http://47.99.138.113:8761/eureka/